### ISSUE TITLE
Switching project doesn't reset control state 

### ISSUE THREAD

**Issue by smunaut** [TinyTapeout/tt-micropython-firmware#18]
First, I'm not sure if it's a commander or SDK thing.

But the issue is that when plugging a board, connected to commander factory test, selecting "Factory Test" ( project 1 ).
`ui_in[0]` ends up already being driven to `1` by default ...

**Comment by urish** [comment]
I believe this is by design: 

https://github.com/TinyTapeout/tt-micropython-firmware/blob/3288485bf974f8b5498ddc21c86174abe9741ee2/src/config.ini#L61

However, looks like config.ini could use some cleanup + have the naming updated to match the new SDK pin names. 

Also, IMHO, setting the inputs by default is "too much magic" and we shouldn't do it (maybe only for tt_um_factory_test, and only upon boot)

**Comment by psychogenic** [comment]
I resolved this in commander with https://github.com/TinyTapeout/tt-commander-app/commit/fd93b1ec8c267026a1cd2eabd805bb1ca07bb9e4 and https://github.com/TinyTapeout/tt-commander-app/commit/3b3167705d701005074baf3b7e73f7b0e4ccb105
